services:
  - type: web
    name: instabot
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TEMP_DIR
        value: downloads
      - key: MAX_FILE_SIZE_MB
        value: 50
